### ISSUE TITLE
ZATCA 2nd Phase QR

### ISSUE THREAD

**Issue by Harisul44** [mrsool/zatca#14] opened 2022-06-15 08:15 UTC
We want to integrate Zatca 2nd phase QR? Can you help us?

**Comment by obahareth** [comment] 2022-06-24 09:17
That's the plan @Harisul44, but I still need to find someone from ZATCA to connect with as the requirements are still unclear from the documentation.

I am currently unable to get access to the cryptographic stamps because I don't have access to the Taxpayer portal. I will try reaching out to ZATCA.

<img width="1076" alt="CleanShot 2022-06-24 at 12 16 53@2x" src="https://user-images.githubusercontent.com/3428118/175504881-07e9b07b-10ba-49ed-b110-cd878bebd646.png">

**Comment by obahareth** [comment] 2022-08-26 12:35
Closing this as a duplicate of #7.

**Closed by obahareth** 2022-08-26 12:35 UTC
